language: generic
sudo: required
services:
  - docker

before_install:
  - docker-compose -f docker-compose-dev.yml up --build
#  - docker build -t camposinhosr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true camposinhosr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-385491363794"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
