language: generic
sudo: required
services:
  - docker

before_install:
#  - docker-compose -f docker-compose-dev.yml up --build
  - docker build -t camposinhosr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true camposinhosr/docker-react npm run test -- --coverage
